import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import type { App } from 'vue'

/** ───── fas (solid) ───── */
import {
  faAngleRight,
  faArrowLeft,
  faArrowRight,
  faBars,
  faBell,
  faBuilding,
  faBullhorn,
  faCalendarCheck,
  faChair,
  faChartLine,
  faChartPie,
  faCheck,
  faCheckCircle,
  faCheckDouble,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faCloudUploadAlt,
  faConciergeBell,
  faEnvelope,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFileArchive,
  faFileDownload,
  faFileImport,
  faFilePdf,
  faFileSignature,
  faFileUpload,
  faFingerprint,
  faFireAlt,
  faGlobe,
  faHistory,
  faImage,
  faImages,
  faInfoCircle,
  faLayerGroup,
  faLock,
  faMapMarkerAlt,
  faMicrophone,
  faMousePointer,
  faPaperPlane,
  faPencilAlt,
  faPhone,
  faPlus,
  faQrcode,
  faSave,
  faSearch,
  faSearchMinus,
  faShieldAlt,
  faSignOutAlt,
  faSortAmountDown,
  faSpinner,
  faStar,
  faTable,
  faTicketAlt,
  faTimes,
  faTimesCircle,
  faToggleOff,
  faToggleOn,
  faTrashAlt,
  faUser,
  faUserCog,
  faUserEdit,
  faUserShield,
  faUserTie,
  faUserTimes,
  faUsers,
  faWallet,
} from '@fortawesome/free-solid-svg-icons'

/** ───── far (regular) ───── */
import {
  faCalendar as farCalendar,
  faCalendarAlt as farCalendarAlt,
  faClock as farClock,
  faCalendarCheck as farCalendarCheck,
} from '@fortawesome/free-regular-svg-icons'

/** ───── fab (brands) ───── */
import { faFacebookF } from '@fortawesome/free-brands-svg-icons'

/** Register every icon so the SVG component can find them by prefix+name. */
export function registerFontAwesome(app: App) {
  library.add(
    /* solid */
    faArrowLeft,
    faArrowRight,
    faBars,
    faBell,
    faBuilding,
    faBullhorn,
    faCalendarCheck,
    faChair,
    faChartLine,
    faChartPie,
    faCheck,
    faCheckCircle,
    faCheckDouble,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faCircle,
    faClipboardCheck,
    faClipboardList,
    faClock,
    faCloudUploadAlt,
    faConciergeBell,
    faEnvelope,
    faExclamationCircle,
    faExclamationTriangle,
    faEye,
    faEyeSlash,
    faFileArchive,
    faFileDownload,
    faFileImport,
    faFilePdf,
    faFileSignature,
    faFileUpload,
    faFingerprint,
    faFireAlt,
    faGlobe,
    faHistory,
    faImage,
    faImages,
    faInfoCircle,
    faLayerGroup,
    faMapMarkerAlt,
    faMicrophone,
    faMousePointer,
    faPaperPlane,
    faPhone,
    faPlus,
    faQrcode,
    faSearch,
    faSearchMinus,
    faShieldAlt,
    faSignOutAlt,
    faSortAmountDown,
    faSpinner,
    faStar,
    faTable,
    faTicketAlt,
    faTimes,
    faTimesCircle,
    faToggleOff,
    faToggleOn,
    faTrashAlt,
    faUser,
    faUserCog,
    faUserEdit,
    faUserShield,
    faUserTie,
    faUserTimes,
    faUsers,
    faWallet,
    /* regular (aliased → use prefix 'far') */
    farCalendar,
    farCalendarAlt,
    farCalendarCheck,
    farClock,
    /* brands */
    faFacebookF,
  )

  app.component('FontAwesomeIcon', FontAwesomeIcon)
}
